#!/bin/bash
set -eux

env

APP_DIR=/srv/conda/app
mkdir $APP_DIR
pushd $APP_DIR
# Desktop applications
# Fiji

wget https://downloads.imagej.net/fiji/archive/20201104-1356/fiji-nojre.zip
unzip -q fiji-nojre.zip
rm fiji-nojre.zip

# Fix Fiji issue
mv Fiji.app/jars/FilamentDetector-1.0.0.jar Fiji.app/jars/FilamentDetector-1.0.0.jar.disabled

# Update Fiji
Fiji.app/ImageJ-linux64 --update update

# Install xpra
git clone --depth 1 https://github.com/Xpra-org/xpra
cd xpra
python3 ./setup.py install
cd ../ && rm -rf xpra

git clone --depth 1 https://github.com/Xpra-org/xpra-html5
cd xpra-html5
python3 ./setup.py install /srv/conda/envs/notebook/share/xpra/www

pushd $REPO_DIR/xpra_server
# Configure jupyter-server-proxy VNC
# https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html#specifying-config-from-python-packages
pip install .
python -c "from pkg_resources import iter_entry_points; print(list(iter_entry_points(group='jupyter_serverproxy_servers')))"
popd