#!/bin/bash
set -eux

env

# Desktop applications
# Fiji and OMERO insight

# Use JDK in conda
# export JAVA_HOME=/opt/conda/bin

wget https://downloads.imagej.net/fiji/archive/20201104-1356/fiji-nojre.zip
unzip -q fiji-nojre.zip
rm fiji-nojre.zip

# Back it up to avoid breaking the Fiji after updating
# https://forum.image.sc/t/fiji-wont-start-after-updating/55605/3
cp Fiji.app/ImageJ-linux64 Fiji.app/ImageJ-linux64-stable

# Fix Fiji issue
mv Fiji.app/jars/FilamentDetector-1.0.0.jar Fiji.app/jars/FilamentDetector-1.0.0.jar.disabled

# Update Fiji
Fiji.app/ImageJ-linux64-stable --update add-update-site MoBIE https://sites.imagej.net/MoBIE/
Fiji.app/ImageJ-linux64-stable --update update

# Fix the launcher
cp Fiji.app/ImageJ-linux64-stable Fiji.app/ImageJ-linux64


pushd ${HOME}/xpra_server

# Configure jupyter-server-proxy xpra
# https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html#specifying-config-from-python-packages
pip install -e .
python -c "from pkg_resources import iter_entry_points; print(list(iter_entry_points(group='jupyter_serverproxy_servers')))"

popd