#!/bin/sh
set -eux

# disable the startup dialog
export XFCE_PANEL_MIGRATE_DEFAULT=1
export DISPLAY=:1.0
ln -s "$CONDA_DIR/vnc/Desktop"

SCRIPT_PATH=`dirname "$0"`
bash ${SCRIPT_PATH}/dumpServerConfig.sh & 

if [[ "$*" == *"--NotebookApp.allow_origin="* ]]; then
exec "$@" # for running with Binder
else
exec "$@" --NotebookApp.allow_origin="*" # for running with local repo2docker
fi
