#!/bin/sh
set -eux

# disable the startup dialog
export XFCE_PANEL_MIGRATE_DEFAULT=1
export DISPLAY=:1.0
ln -s "$CONDA_DIR/vnc/Desktop"

# Start ImJoy elFinder
export BINDER_BASE_URL=`jupyter notebook list --json | python3 -c 'import json; import sys; print(json.load(sys.stdin)["base_url"])'`

exec "$@"
